config/routes.rb
App1::Application.routes.draw do

  root :to => 'home#index'

  resources :users
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  #validates [:name,:color,:user_id], :presence => true
  validates :name, :presence => true
  validates :color, :presence => true
  validates :user_id, :numericality => { :greater_than => 0}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items, dependent: :destroy
  validates :name, :presence => true
  validates :last_name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # GET /items
  def index
    @items = Item.find(:all, :include => :user)
    @users_count = User.count
    render :layout => false if (request.xhr?)
  end

  # GET /items/new
  def new
    @Item = Item.new
    @users = User.all
    render :layout => false if (request.xhr?)
  end

  # GET /items/:id/edit
  def edit
    @Item = Item.find(params[:id])
    @users = User.all
    render :layout => false if (request.xhr?)
  end
  
  # POST /items
  def create
    @Item = Item.new(params[:item])


    if @Item.save
      if request.xhr?
        render :json => {"error" => "false", "item" => @Item, }
      else
        redirect_to items_path, notice: 'Item created successfully'
      end
    else
      if request.xhr?
        render :json => {"error" => "true", "errors" => @Item.errors}
      else
        @users = User.all
        render action: 'new'
      end
    end
     
   
  end

  # PUT /items/:id
  def update
    @Item = Item.find(params[:id])
    @Item.attributes = params[:item]
    

    if @Item.save
      if request.xhr?
        render :json => {"error" => "false", "item" => @Item, }
      else
        redirect_to items_path, notice: 'Item updated'
      end
    else
      if request.xhr?
        render :json => {"error" => "true", "errors" => @Item.errors}
      else
        @users = User.all
        render action: 'edit'
      end
    end
  end

  # DELETE /Item/:id
  def destroy
    @Item = Item.find(params[:id])
    @Item.destroy

    if request.xhr?
      render :json => {"delete" => "true", "item_deleted" => @Item}
    else
      redirect_to items_path, notice: 'Item deleted'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  def index
    @users = User.all
    render :layout => false if (request.xhr?)
  end

  # GET /users/new
  def new
    @user = User.new
    render :layout => false if (request.xhr?)
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
    render :layout => false if (request.xhr?)
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
    render :action => :user_items, :layout => false if (request.xhr?)
  end

  # PUT /users/:id
  def update
    @user = User.find(params[:id])
    @user.attributes = params[:user]

    if @user.save
      if request.xhr?
        render :json => {"error" => "false", "user" => @user}
      else
        redirect_to users_path, notice: 'User updated'
      end
    else
      if request.xhr?
        render :json => {"error" => "true", "errors" => @user.errors}
      else
        render action: 'edit'
      end
    end

  end

  # POST /users
  def create
    @user = User.new(params[:user])

    if @user.save
      if request.xhr?
        #render :json => {"error" => "false", "user" => @user, 'select_for_users' => (render :partial=>'blabla', :locals=>{'users'=>@users})}
        render :json => {"error" => "false", "user" => @user, }
      else
        redirect_to users_path, notice: 'User created successfully'
      end
    else
      if request.xhr?
        render :json => {"error" => "true", "errors" => @user.errors}
      else
        render action: 'new'
      end
    end
  end

  # DELETE /user/:id
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if request.xhr?
      render :json => {"delete" => "true", "user_deleted" => @user}
    else
      redirect_to users_path, notice: 'User deleted'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1>App</h1>
<div id="links">
     <div>
         <%=  link_to "Manage Users", users_path %>
  </div>
  <div>
    <%=  link_to "Manage Items", items_path %>
  </div>
  <div id="drop_down">
    <%= select :home, :users, [["Select a User:", 0]] + @users.map {|u| [u.name,u.id]} %>
  </div>
</div>
<div id="ajax_content" style="clear: both"></div>

app/views/items/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<%= form_for(@Item, remote: true,:html => { :'data-type' => 'json' }) do |f| %>
  <table class="info">
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :color %></td>
      <td><%= f.text_field :color %></td>
    </tr>
    <tr>
      <td>User</td>
      <td><%= f.select :user_id, [["Select one", 0]] + @users.map {|u| [u.name,u.id]} %></td>
      <% if (!@Item.errors[:user_id].blank?) %>
        <td><label style="color:red">You have to select a user</label></td>
      <% end %>
    </tr>
  </table>
  <div class="action">
    <%=f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h2>Editing Item</h2>

<div id="notice"></div>
<div id="edit_item_form">
  <%= render 'form' %>
</div>
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h2>Items</h2>
<p id="notice"><%= notice %></p>
<% if @items.size > 0 %>
  <%= link_to 'Add new Item', new_item_path, :id => "add_new_item"  %>
  <br />
  <table id="item_list">
    <tr>
      <td><b>Name</b></td>
      <td><b>Color</b></td>
      <td><b>User</b></td>
    </tr>
    <% @items.each do |item| %>
      <tr id="item_<%= item.id %>">
        <td><%= item.name %></td>
        <td><%= item.color %></td>
        <td><%= item.user.name %> </td>
        <td><%= link_to image_tag('edit.png', :border => 0), edit_item_path(item), :class=>'edit_item' %></td>
        <td><%= link_to image_tag('delete.gif'), item, confirm: 'Are you sure?', method: :delete, remote: true, :class => 'delete_item' %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <% if @users_count > 0 %>
    <p>No item have been defined yet</p>
    <%= link_to 'Create one now',new_item_path, :id => "add_new_item"  %>
  <% else %>
    <p>In order to create an Item, you must have at least 1 user.</p>
    <p><%= link_to "Create one now", new_user_path, :id => "add_new_item"  %></p>
  <% end %>
  <br />
<% end %>

app/views/items/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<h2>Create new Item</h2>

<div id="notice"></div>
<div id="new_item_form">
  <%= render 'form' %>
</div>
<br />
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<%= form_for(@user, remote: true,:html => { :'data-type' => 'json' } ) do |f| %>
  <table class="info">
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :last_name %></td>
      <td><%= f.text_field :last_name %></td>
    </tr>
  </table>
  <div class="action">
    <%=f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h2>Editing User</h2>

<div id="notice"></div>
<div id="edit_user_form">
<%= render 'form' %>
</div>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>Users</h2>
<p id="notice"><%= notice %></p>
<% if @users.size > 0 %>
  <%= link_to 'Add new User', new_user_path, :id => "add_new_user" %>
  <br />
  <table id="user_list">
    <tr>
      <td><b>Name</b></td>
      <td><b>Last Name</b></td>
    </tr>
    <% @users.each do |user| %>
      <tr id="user_<%= user.id %>">
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to image_tag('edit.png', :border => 0), edit_user_path(user), :class=>'edit_user' %></td>
        <td><%= link_to image_tag('delete.gif'), user, confirm: 'Are you sure?', method: :delete, remote: true, :class => 'delete_user' %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>No user have been defined yet</p>
  <%= link_to 'Create one now',new_user_path, :id => "add_new_user" %>
<% end %>

app/views/users/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<h2>Create new User</h2>

<div id="notice"></div>
<div id="new_user_form">
  <%= render 'form' %>
</div>
<br />
<%= link_to 'Back', users_path %>

app/views/users/user_items.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<% if @user.items.size > 0 %>
  <div>Items:</div>
  <table border="1">
    <tr>
      <td>Name:</td>
      <td>Color:</td>
    </tr>
    <% @user.items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.color %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div>This User have no items</div>
<% end %>